version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/elderly_health_platform/db.sqlite3
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  sqlite_data: