# Generated by Django 5.1.4 on 2024-12-08 02:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '管理员', 'verbose_name_plural': '管理员'},
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_elderly',
        ),
        migrations.RemoveField(
            model_name='user',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录者'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='activity_level',
            field=models.CharField(blank=True, max_length=20, verbose_name='活动强度'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='activity_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='活动类型'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='breakfast',
            field=models.CharField(blank=True, max_length=200, verbose_name='早餐'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='date',
            field=models.DateField(verbose_name='记录日期'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='dinner',
            field=models.CharField(blank=True, max_length=200, verbose_name='晚餐'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='lunch',
            field=models.CharField(blank=True, max_length=200, verbose_name='午餐'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='睡眠时长'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='water_intake',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='饮水量(升)'),
        ),
        migrations.CreateModel(
            name='Elderly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='居住地址')),
                ('medical_history', models.TextField(blank=True, verbose_name='既往病史')),
                ('emergency_contact', models.CharField(max_length=50, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(max_length=20, verbose_name='紧急联系电话')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '老年人信息',
                'verbose_name_plural': '老年人信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='elderly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_records.elderly', verbose_name='老年人'),
        ),
    ]
