# Generated by Django 5.1.4 on 2024-12-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0002_alter_user_options_remove_healthrecord_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='recommendation',
            field=models.TextField(blank=True, null=True, verbose_name='个性化建议'),
        ),
    ]
